### ISSUE TITLE
Uncaught TypeError: Cannot read property 'withTracker' of undefined

### ISSUE THREAD

**Issue by shacharsol** [ardatan/meteor-webpack#24]
I'm using react with metoer example and the tracker is not working:
Uncaught TypeError: Cannot read property 'withTracker' of undefined
    at Object.eval (App.jsx:161)
    at eval (App.jsx:189)
    at Object../client/ui/App.jsx (bundle.js:812)
    at __webpack_require__ (bundle.js:712)
    at fn (bundle.js:95)
    at eval (main.jsx:9)
    at Object../client/main.jsx (bundle.js:788)
    at __webpack_require__ (bundle.js:712)
    at bundle.js:764
    at bundle.js:767

**Comment by ardatan** [comment]
Thank you for your collaboration! This issue is due to some changes in Meteor's babel packages, that's why we need to update them by the following command;
```
meteor update babel-compiler ecmascript modules # mandatory
```
https://github.com/meteor/meteor/issues/9905

**Comment by andreasemprebon** [comment]
Hi @s7dhansh ,
check if the meteor package `react-meteor-data` is installed (look into `.meteor/packages`).

If not, install it, this should fix the issue:
`meteor add react-meteor-data`

**Comment by s7dhansh** [comment]
@andreasemprebon The package is already installed. Everything is working without webpack. Error comes with webpack.

**Comment by andreasemprebon** [comment]
@s7dhansh I came across the same issue today and my (trivial) mistake was not having the `react-meteor-data` installed.
Have you tried reinstalling all meteor packages?
I don't want to give you false suggestions, I replied because my error was the same and has been trivially resolved. I have a feeling that the issue is not in webpack itself but in a strange condition in which your project is now. Maybe try build a small, cut to the bone project and see if it fails also there or not.
