### ISSUE TITLE
Has anyone dealt with nested imports?

### ISSUE THREAD

**Issue by jolim24601** [ardatan/meteor-webpack#28]
Working on migrating a meteor 1.7 app to use webpack but I keep getting the nested imports error. Has anyone dealt with this and if so what did you do? Most of the imports are wrapped in `Meteor.isServer` blocks.

**Comment by ardatan** [comment]
`meteor-webpack` compiles client and server codes seperately. That's why, I recommend you to use seperate endpoints for your client and server code instead of seperating your codes with `Meteor.isServer`, because the blocks in `Meteor.isServer` condition will be compiled for client as well; so this is error prone.

**Comment by jolim24601** [comment]
Thanks for replying @ardatan . This isn't really a bug however, I was asking for technical advice as I'm dealing with a fairly large codebase. Separating client from server code would be a huge task so I was wondering if anyone has dealt with this issue before. I was thinking potentially of using the [reify babel plugin](https://github.com/benjamn/reify/tree/master/packages/babel-plugin-transform-es2015-modules-reify) and then using reify on client and server at runtime, essentially this would mirror what meteor does. I was wondering if there were other options besides this. Thanks for your work.
