### ISSUE TITLE
Not compatible with module resolver? (babel-plugin-module-resolver)

### ISSUE THREAD

**Issue by tjramage** [ardatan/meteor-webpack#30]
We use custom aliases throughout our app in order to make importing modules much easer (see https://www.npmjs.com/package/babel-plugin-module-resolver for more info).

We have defined our custom modules via `.babelrc` (and this works with Meteor). However, I cannot seem to get these to work with this meteor-webpack package. Can you confirm if this is a compatibility issue? Are you able to update the example configs to show this working?

Every time it tries to compile, it complains about not being able to resolve paths (as it's not resolving the custom alias paths for our imports).

Thanks for your help!

**Comment by dobesv** [comment]
You may want to ensure your babel config is being used at all, maybe put something bogus in there to be sure.  In theory the babel plugin will rewrite the absolute imports to relative ones before webpack scans it.  You can also setup the same rules in your `webpack.config.js` as in the `.babelrc` and see if that helps.  I'm just getting started with this stuff myself, though, perhaps someone more experienced will chime in.

**Comment by tjramage** [comment]
Hey, thanks @dobesv. Indeed, I did wonder if `.babelrc` was being picked up at all — so I did exactly what you said and put them straight into the `webpack.config.js` instead. However, I still experienced the same issues...

**Comment by ardatan** [comment]
This is not a compability issue at all; because babel inside Meteor’s bundler ‘ecmascript’ uses it. But when you install our package, it replaces its functionality by Webpack. Thus, there will be no babel compiler until you add it to Webpack.
As a result, there are some options to use aliases with Webpack;
First option is that you can use babel-loader by defining same options in ‘babelrc’ file
Or
Second option is that you can use Webpack’s aliasing which you can find in Webpack’s own documentation.

Other option is not to use Webpack if Meteor’s own bundler works for you.
