### ISSUE TITLE
HMR is working but not always

### ISSUE THREAD

**Issue by filipenevola** [ardatan/meteor-webpack#5]
Hello, I'm testing HMR with your react example project, on Chrome.

It's working the first time and after it stops to work then I need to refresh the page (reload), sometimes even it is not making my changes appear then I need to clean the storage of the application because even with server restart it continues to show the same content.

Are you experiencing this too? Have you tested it in a bigger application? How can I help?

**Comment by filipenevola** [comment]
Hello @ardatan , I think this one is the most critical one because we need to be sure it's working very well in this small example to continue to improve it and make it work in bigger projects.

Please let me know if I can help you.

**Comment by ardatan** [comment]
Hello @filipenevola we need to specify the problem.

**Comment by ardatan** [comment]
@filipenevola
Could you check out new example for react?

**Comment by filipenevola** [comment]
Hello, sorry for my late response, I'm in the middle of a trip, anyway, it's working better now, I was able to do multiple changes on the client but after my first change on the server, I need to refresh the browser to start to see changes on the client again.

Is that expected?

Good job! It's getting better what is great.

**Comment by mikaelwecode** [comment]
Hello. 
I experience the same when I update code in the in the imports/api folder. But I also got this error in the console
"[HMR] Update check failed: SyntaxError: Unexpected token < in JSON at position 0". I am Trying the React example.

**Comment by ardatan** [comment]
Actually, it shouldn't refresh like Meteor CLI does because nothing changes in client, but it is a little bit different in our case. When server restarts, we lose HMR connection once. And it doesn't reconnect like Meteor CLI does. I am still trying to figure out this. I think I need some trick in case of server refresh.

**Comment by Gywem** [comment]
Today, I have tried the approach mentioned above. Making Meteor to ignore all changes via `.meteorignore` works fine, however triggering by code a Meteor server restart isn't.

What I tried so far is:
- Enable the server configuration to create the bundle on the disk filesystem, within a `dist/server` folder, in order to "react" on any change and restart the server. While any explicit modification within the `dist/server` folder makes the server to restart, I could't been able to achieve the same by an implicit change due to the webpack compilation.
- Make the `webpack-dev-middleware` plugin to add and remove a file using the `fs` lib within the `dist/server` folder after a dev webpack server compilation. But again, the meteor server doesn't detect this change and then isn't restarted.

I have tried to find other ways to act on the Meteor server but feels like is not possible, or nobody has tried it before. Not sure which other options we have to solve this issue.

**Comment by ardatan** [comment]
Hello @Gywem,
Thanks for your `.meteorignore` idea. I used this to prevent triggering Meteor's bundler. 
Then I did several changes on `webpack-dev-middleware` package;

- I added server compiler to webpack-dev-middleware like client compiler.

- Now it clears publish and method handlers before executing last compiled server bundle, then executes. So, it works similar way on server-side with HMR on client-side from now on.

After last changes which I haven't released yet, server and client compilations are almost independent and server restart doesn't force to recompile client code.

**Comment by Gywem** [comment]
Feels like a neater approach you accomplished. Really excited to see it on code and understand better how Webpack bundler works. Thanks a lot! 😄

**Comment by ardatan** [comment]
The server-side code can benefit HMR like client-side without Meteor's slow recompilation of `already webpack-compiled code`.
I will document this on `README`.
The solution is to add `.meteorignore` which has almost all directories such as `server/`, `client/` and `imports/` except `webpack.config.js` to restart webpack in case of change in configuration, then adding 
```js
...
devServer: {
    hot: true
}
```
for both client and server configuration. Then you can obtain HMR experience for both server and client!

Please try and give me feedback about this new feature, then we can close this issue immediately.

https://github.com/ardatan/meteor-webpack/releases/tag/0.0.3

**Comment by Gywem** [comment]
This sounds amazing!

I've set the basic configuration for the react example in a fork, https://github.com/Gywem/meteor-webpack/tree/test-server-reload.

The only thing I've noted is that any change on server code is not taking effect on the refresh the app. I guess that is because the meteor server is not reloaded and then doesn't have the new code to display. Have you sorted out a way to inject the changes on the meteor server being running?

I recorded a video showing you client and server HMR, and the issue explained above with the server. Check it out [here](https://monosnap.com/file/JLzaWEikVFrvMJeO4rjGY77L0G4D5h).

I followed the instructions in the "readme" to set it up, may I missing something? Can you check it on my branch?

**Comment by Gywem** [comment]
Thanks!

Not sure why but after pulling changes from `0.0.3_1` version, I get: 
<img width="726" alt="todo list 2018-04-26 21-45-52" src="https://user-images.githubusercontent.com/2581993/39328339-5b51657e-499b-11e8-98d5-57419f4f74f1.png">

Did the last release include other kind of changes? I just noted that some meteor packages upgraded. Not sure if that would be related. I'll look deeper into this on the weekend.

**Comment by Gywem** [comment]
I have solved the problem I mentioned previously by downgrading the emacscript version from `0.10.8` to the previously used `0.10.7`. Then I have got the issue reported here, https://github.com/ardatan/meteor-webpack/issues/9. We may move the discussion there for such. But what about the one that is solved by getting back the `emacscript`, do you happen to know why happens?

**Comment by royGil** [comment]
@Gywem 

Just update webpack and related packages to their latest version
